import { useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowDownToLine, ArrowRight, Check, CircleUserRound, FileUp, Plus, Trash2, UploadCloud, X } from 'lucide-react'
import { api } from '../api'
import { normalizeProfile } from '../api/normalize'
import type { Education, Experience, Profile } from '../api'
import { useToast } from '../App'
import { EmptyState, ErrorState, Field, LoadingRows, PageHeading, SectionTitle, TagInput } from '../components/ui'

const blankProfile: Profile = { full_name: '', headline: '', email: '', phone: '', location: '', links: [], summary: '', experience: [], education: [], skills: { languages: [], frameworks: [], tools: [] }, languages: [], certifications: [], updated_at: null }
const newExperience = (): Experience => ({ id: `exp_${Date.now()}`, company: '', title: '', location: '', start_date: '', end_date: null, bullets: [], skills: [] })
const newEducation = (): Education => ({ id: `edu_${Date.now()}`, school: '', degree: '', field: '', start_date: '', end_date: null, gpa: '' })

function ImportModal({ onClose, onImported }: { onClose: () => void; onImported: (profile: Profile) => void }) {
  const [file, setFile] = useState<File | null>(null)
  const [preview, setPreview] = useState<Profile | null>(null)
  const input = useRef<HTMLInputElement>(null)
  const mutation = useMutation({ mutationFn: api.importProfile, onSuccess: setPreview })
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !mutation.isPending) onClose() }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close) }, [onClose, mutation.isPending])
  const selectFile = (selected?: File) => {
    if (!selected) return
    if (mutation.isPending) return
    if (!/\.(pdf|docx|txt|md)$/i.test(selected.name)) return setError('PDF, DOCX, TXT veya MD dosyası seç.')
    if (selected.size > 10 * 1024 * 1024) return setError('Dosya 10 MB’tan küçük olmalı.')
    setError(null)
    setFile(selected)
    mutation.mutate(selected)
  }
  const [error, setError] = useState<string | null>(null)
  const close = () => { if (!mutation.isPending) onClose() }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) close() }}><div className="modal import-modal" role="dialog" aria-modal="true" aria-labelledby="import-title"><button className="icon-button modal-close" aria-label="Kapat" disabled={mutation.isPending} onClick={close}><X size={20} /></button><div className="modal-icon"><FileUp size={23} /></div><p className="step-label">{preview ? '3 / 3 · Kontrol et' : mutation.isPending ? '2 / 3 · Okunuyor' : '1 / 3 · CV yükle'}</p><h2 id="import-title">{preview ? 'Bilgileri gözden geçir' : mutation.isPending ? 'CV okunuyor…' : 'Mevcut CV’ni yükle'}</h2><p>{preview ? 'Çıkarılan bilgileri profil sayfasında düzenleyebilir, ardından kaydedebilirsin.' : 'PDF, DOCX, TXT veya MD dosyasındaki bilgileri profil taslağına dönüştürelim. Okuma 10–30 saniye sürebilir.'}</p>{preview ? <div className="import-preview"><strong>{preview.full_name || 'İsim bulunamadı'}</strong><span>{preview.headline || 'Başlık bulunamadı'}</span><div><span>{preview.experience.length} deneyim</span><span>{preview.education.length} eğitim</span><span>{Object.values(preview.skills).flat().length} yetenek</span></div></div> : <div className={`upload-zone ${mutation.isPending ? 'busy' : ''}`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); selectFile(event.dataTransfer.files[0]) }}><UploadCloud size={28} /><strong>{mutation.isPending ? `${file?.name} okunuyor…` : file?.name || 'Dosyanı buraya bırak'}</strong><span>veya</span><button type="button" className="button secondary" disabled={mutation.isPending} onClick={() => input.current?.click()}>Dosya seç</button><input ref={input} type="file" accept=".pdf,.docx,.txt,.md" hidden disabled={mutation.isPending} onChange={event => selectFile(event.target.files?.[0])} /></div>}{(error || mutation.error) && <p role="alert" className="error-message">{error || mutation.error?.message}</p>}<div className="modal-actions"><button className="button secondary" disabled={mutation.isPending} onClick={close}>Vazgeç</button>{preview && <button className="button primary" onClick={() => { onImported(preview); close() }}>Taslağa aktar <ArrowRight size={17} /></button>}</div></div></div>
}

export function ProfilePage() {
  const profileQuery = useQuery({ queryKey: ['profile'], queryFn: api.getProfile })
  const [draft, setDraft] = useState<Profile | null>(null)
  const [importOpen, setImportOpen] = useState(false)
  const [dirty, setDirty] = useState(false)
  const queryClient = useQueryClient()
  useEffect(() => { if (profileQuery.data && !dirty) setDraft(profileQuery.data) }, [profileQuery.data, dirty])
  const toast = useToast()
  const save = useMutation({ mutationFn: (profile: Profile) => api.saveProfile(normalizeProfile(profile)), onSuccess: saved => { setDraft(saved); setDirty(false); queryClient.setQueryData(['profile'], saved); toast('Profil kaydedildi.', 'success') }, onError: error => toast(error.message, 'error') })
  const update = (change: Partial<Profile>) => { setDraft(current => ({ ...(current || blankProfile), ...change })); setDirty(true) }
  const updateExperience = (id: string, change: Partial<Experience>) => update({ experience: (draft?.experience || []).map(item => item.id === id ? { ...item, ...change } : item) })
  const updateEducation = (id: string, change: Partial<Education>) => update({ education: (draft?.education || []).map(item => item.id === id ? { ...item, ...change } : item) })
  if (profileQuery.isLoading) return <LoadingRows count={5} />
  if (profileQuery.isError) return <ErrorState error={profileQuery.error} onRetry={() => profileQuery.refetch()} />
  const profile = draft || blankProfile
  return <><PageHeading eyebrow="Kariyer dosyan" title="Profil" description="Başvuru paketlerinin kaynağı burası. Bilgilerini güncel tutman yeterli." actions={<button className="button primary" disabled={!dirty || save.isPending} onClick={() => save.mutate(profile)}><Check size={17} /> {save.isPending ? 'Kaydediliyor…' : 'Değişiklikleri kaydet'}</button>} />
    <div className="import-banner"><div className="import-banner-icon"><FileUp size={22} /></div><div><strong>CV’nden hızlıca başlayabilirsin</strong><p>Mevcut CV’ni yükle, bilgileri gözden geçirip profiline aktar.</p></div><button className="button secondary" onClick={() => setImportOpen(true)}><ArrowDownToLine size={17} /> CV yükle</button></div>
    <div className="profile-layout"><nav className="profile-anchor-nav" aria-label="Profil bölümleri"><span>Profil bölümleri</span>{[['personal', 'Kişisel bilgiler'], ['summary', 'Özet'], ['experience', 'Deneyim'], ['education', 'Eğitim'], ['skills', 'Yetenekler'], ['languages', 'Diller ve sertifikalar']].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="profile-sections">
      <section className="content-panel form-section" id="personal"><SectionTitle title="Kişisel bilgiler" /><div className="form-grid"><Field label="Ad soyad"><input aria-label="Ad soyad" value={profile.full_name} onChange={event => update({ full_name: event.target.value })} /></Field><Field label="Profesyonel başlık"><input aria-label="Profesyonel başlık" value={profile.headline} onChange={event => update({ headline: event.target.value })} placeholder="Backend Developer" /></Field><Field label="E-posta"><input aria-label="E-posta" type="email" value={profile.email} onChange={event => update({ email: event.target.value })} /></Field><Field label="Telefon"><input aria-label="Telefon" value={profile.phone || ''} onChange={event => update({ phone: event.target.value })} /></Field><Field label="Konum"><input aria-label="Konum" value={profile.location || ''} onChange={event => update({ location: event.target.value })} /></Field></div><div className="repeat-list">{profile.links.map((link, index) => <div className="inline-fields" key={index}><input aria-label={`Bağlantı ${index + 1} adı`} placeholder="GitHub" value={link.label} onChange={event => update({ links: profile.links.map((item, i) => i === index ? { ...item, label: event.target.value } : item) })} /><input aria-label={`Bağlantı ${index + 1} adresi`} type="url" placeholder="https://" value={link.url} onChange={event => update({ links: profile.links.map((item, i) => i === index ? { ...item, url: event.target.value } : item) })} /><button className="icon-button" aria-label="Bağlantıyı sil" onClick={() => update({ links: profile.links.filter((_, i) => i !== index) })}><Trash2 size={17} /></button></div>)}</div><button className="text-button" onClick={() => update({ links: [...profile.links, { label: '', url: '' }] })}><Plus size={16} /> Bağlantı ekle</button></section>
      <section className="content-panel form-section" id="summary"><SectionTitle title="Kısa özet" /><p className="section-help">Deneyimini birkaç cümlede anlat. Başvuru paketleri bu metinden yararlanır.</p><textarea aria-label="Kısa özet" rows={5} value={profile.summary} onChange={event => update({ summary: event.target.value })} placeholder="Neler üzerinde çalıştın, hangi alanlarda güçlüsün?" /></section>
      <section className="content-panel form-section" id="experience"><SectionTitle title="Deneyim" action={<button className="text-button" onClick={() => update({ experience: [...profile.experience, newExperience()] })}><Plus size={16} /> Deneyim ekle</button>} />{profile.experience.length ? profile.experience.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-head"><strong>{item.title || `Deneyim ${index + 1}`}</strong><button className="icon-button" aria-label="Deneyimi sil" onClick={() => update({ experience: profile.experience.filter(exp => exp.id !== item.id) })}><Trash2 size={17} /></button></div><div className="form-grid"><Field label="Pozisyon"><input aria-label="Pozisyon" value={item.title} onChange={event => updateExperience(item.id, { title: event.target.value })} /></Field><Field label="Şirket"><input aria-label="Şirket" value={item.company} onChange={event => updateExperience(item.id, { company: event.target.value })} /></Field><Field label="Konum"><input aria-label="Deneyim konumu" value={item.location || ''} onChange={event => updateExperience(item.id, { location: event.target.value })} /></Field><Field label="Başlangıç"><input aria-label="Başlangıç ayı" type="month" value={item.start_date || ''} onChange={event => updateExperience(item.id, { start_date: event.target.value })} /></Field><Field label="Bitiş"><input aria-label="Bitiş ayı" type="month" value={item.end_date || ''} onChange={event => updateExperience(item.id, { end_date: event.target.value || null })} /></Field></div><Field label="Öne çıkan çalışmalar" hint="Her satıra bir madde yaz."><textarea aria-label="Öne çıkan çalışmalar" rows={4} value={item.bullets.join('\n')} onChange={event => updateExperience(item.id, { bullets: event.target.value.split('\n') })} /></Field><Field label="Kullandığın yetenekler"><TagInput items={item.skills} onChange={skills => updateExperience(item.id, { skills })} /></Field></div>) : <EmptyState icon={<CircleUserRound size={24} />} title="Deneyim eklenmedi" description="İş, staj ve gönüllü çalışmalarını burada tutabilirsin." />}</section>
      <section className="content-panel form-section" id="education"><SectionTitle title="Eğitim" action={<button className="text-button" onClick={() => update({ education: [...profile.education, newEducation()] })}><Plus size={16} /> Eğitim ekle</button>} />{profile.education.map((item, index) => <div className="repeat-card" key={item.id}><div className="repeat-head"><strong>{item.school || `Eğitim ${index + 1}`}</strong><button className="icon-button" aria-label="Eğitimi sil" onClick={() => update({ education: profile.education.filter(edu => edu.id !== item.id) })}><Trash2 size={17} /></button></div><div className="form-grid"><Field label="Okul"><input aria-label="Okul" value={item.school} onChange={event => updateEducation(item.id, { school: event.target.value })} /></Field><Field label="Derece"><input aria-label="Derece" value={item.degree || ''} onChange={event => updateEducation(item.id, { degree: event.target.value })} /></Field><Field label="Bölüm"><input aria-label="Bölüm" value={item.field || ''} onChange={event => updateEducation(item.id, { field: event.target.value })} /></Field><Field label="Not ortalaması"><input aria-label="Not ortalaması" value={item.gpa || ''} onChange={event => updateEducation(item.id, { gpa: event.target.value })} /></Field><Field label="Başlangıç"><input aria-label="Eğitim başlangıç ayı" type="month" value={item.start_date || ''} onChange={event => updateEducation(item.id, { start_date: event.target.value })} /></Field><Field label="Bitiş"><input aria-label="Eğitim bitiş ayı" type="month" value={item.end_date || ''} onChange={event => updateEducation(item.id, { end_date: event.target.value || null })} /></Field></div></div>)}{!profile.education.length && <p className="quiet-line">Eğitim bilgisi henüz yok.</p>}</section>
      <section className="content-panel form-section" id="skills"><SectionTitle title="Yetenekler" /><div className="skill-form-grid"><Field label="Programlama dilleri"><TagInput items={profile.skills.languages} onChange={languages => update({ skills: { ...profile.skills, languages } })} /></Field><Field label="Framework ve kütüphaneler"><TagInput items={profile.skills.frameworks} onChange={frameworks => update({ skills: { ...profile.skills, frameworks } })} /></Field><Field label="Araçlar"><TagInput items={profile.skills.tools} onChange={tools => update({ skills: { ...profile.skills, tools } })} /></Field></div></section>
      <section className="content-panel form-section" id="languages"><SectionTitle title="Diller ve sertifikalar" /><h3 className="minor-title">Yabancı diller</h3>{profile.languages.map((item, index) => <div className="inline-fields" key={index}><input aria-label="Dil" placeholder="Dil" value={item.name} onChange={event => update({ languages: profile.languages.map((lang, i) => i === index ? { ...lang, name: event.target.value } : lang) })} /><input aria-label="Seviye" placeholder="Seviye" value={item.level} onChange={event => update({ languages: profile.languages.map((lang, i) => i === index ? { ...lang, level: event.target.value } : lang) })} /><button className="icon-button" aria-label="Dili sil" onClick={() => update({ languages: profile.languages.filter((_, i) => i !== index) })}><Trash2 size={17} /></button></div>)}<button className="text-button" onClick={() => update({ languages: [...profile.languages, { name: '', level: '' }] })}><Plus size={16} /> Dil ekle</button><h3 className="minor-title separated">Sertifikalar</h3>{profile.certifications.map((item, index) => <div className="inline-fields" key={index}><input aria-label="Sertifika adı" placeholder="Sertifika" value={item.name} onChange={event => update({ certifications: profile.certifications.map((cert, i) => i === index ? { ...cert, name: event.target.value } : cert) })} /><input aria-label="Veren kurum" placeholder="Veren kurum" value={item.issuer || ''} onChange={event => update({ certifications: profile.certifications.map((cert, i) => i === index ? { ...cert, issuer: event.target.value } : cert) })} /><input aria-label="Sertifika tarihi" type="month" value={item.date || ''} onChange={event => update({ certifications: profile.certifications.map((cert, i) => i === index ? { ...cert, date: event.target.value } : cert) })} /><button className="icon-button" aria-label="Sertifikayı sil" onClick={() => update({ certifications: profile.certifications.filter((_, i) => i !== index) })}><Trash2 size={17} /></button></div>)}<button className="text-button" onClick={() => update({ certifications: [...profile.certifications, { name: '', issuer: '', date: '' }] })}><Plus size={16} /> Sertifika ekle</button></section>
      <div className="form-bottom"><span>{dirty ? 'Kaydedilmemiş değişiklikler var' : 'Tüm değişiklikler kaydedildi'}</span><button className="button primary" disabled={!dirty || save.isPending} onClick={() => save.mutate(profile)}><Check size={17} /> Kaydet</button></div>
    </div></div>{importOpen && <ImportModal onClose={() => setImportOpen(false)} onImported={imported => update(imported)} />}
  </>
}
