import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Check, Clock3, Compass, Radar, SlidersHorizontal } from 'lucide-react'
import { api } from '../api'
import type { SearchSettings, Seniority } from '../api'
import { useToast } from '../App'
import { useAuth } from '../auth'
import { ErrorState, Field, LoadingRows, PageHeading, SectionTitle, TagInput } from '../components/ui'

const levels: { value: Seniority; label: string }[] = [{ value: 'intern', label: 'Stajyer' }, { value: 'junior', label: 'Junior' }, { value: 'mid', label: 'Mid' }, { value: 'senior', label: 'Senior' }, { value: 'lead', label: 'Lead' }]
const sourceToggles = [{ key: 'remoteok', label: 'RemoteOK' }, { key: 'remotive', label: 'Remotive' }, { key: 'arbeitnow', label: 'Arbeitnow' }, { key: 'adzuna', label: 'Adzuna' }] as const

export function SettingsPage() {
  const settings = useQuery({ queryKey: ['settings'], queryFn: api.getSettings })
  const [draft, setDraft] = useState<SearchSettings | null>(null)
  const [dirty, setDirty] = useState(false)
  const toast = useToast()
  const auth = useAuth()
  const queryClient = useQueryClient()
  useEffect(() => { if (settings.data && !dirty) setDraft(settings.data) }, [settings.data, dirty])
  const save = useMutation({ mutationFn: api.saveSettings, onSuccess: result => { setDraft(result); setDirty(false); queryClient.setQueryData(['settings'], result); toast('Arama ayarları kaydedildi.', 'success') } })
  const update = (change: Partial<SearchSettings>) => { setDraft(current => current ? { ...current, ...change } : current); setDirty(true) }
  if (settings.isLoading) return <LoadingRows count={5} />
  if (settings.isError || !draft) return <ErrorState error={settings.error || new Error('Ayarlar yüklenemedi.')} onRetry={() => settings.refetch()} />
  const [cronMinute, cronHour] = draft.schedule_cron.split(' ')
  const hour = Number(cronHour)
  const minute = Number(cronMinute)
  const scheduleTime = `${String(Number.isInteger(hour) && hour >= 0 && hour < 24 ? hour : 8).padStart(2, '0')}:${String(Number.isInteger(minute) && minute >= 0 && minute < 60 ? minute : 0).padStart(2, '0')}`
  const setScheduleTime = (value: string) => { const [selectedHour, selectedMinute] = value.split(':').map(Number); if (Number.isInteger(selectedHour) && Number.isInteger(selectedMinute)) update({ schedule_cron: `${selectedMinute} ${selectedHour} * * *` }) }
  return <><PageHeading eyebrow="Arama tercihlerin" title="Ayarlar" description="Sana uygun fırsatları bulmak için sınırlarını ve önceliklerini belirle." actions={<button className="button primary" disabled={!dirty || save.isPending} onClick={() => save.mutate(draft)}><Check size={17} /> {save.isPending ? 'Kaydediliyor…' : 'Ayarları kaydet'}</button>} />
    <div className="settings-layout"><div className="settings-lead"><div className="settings-lead-icon"><Compass size={28} /></div><h2>Aradığın işe biraz daha yaklaş.</h2><p>Buradaki tercihler ilan taramasını ve hangi başvuru paketlerinin otomatik hazırlanacağını belirler.</p></div><div className="settings-sections">
      <section className="content-panel form-section"><SectionTitle title="Ne arıyorsun?" /><Field label="Hedef pozisyonlar"><TagInput items={draft.target_roles} onChange={target_roles => update({ target_roles })} placeholder="Pozisyon ekle" /></Field><Field label="Deneyim seviyesi"><div className="choice-list">{levels.map(level => <label className={`choice-chip ${draft.seniority.includes(level.value) ? 'selected' : ''}`} key={level.value}><input type="checkbox" checked={draft.seniority.includes(level.value)} onChange={event => update({ seniority: event.target.checked ? [...draft.seniority, level.value] : draft.seniority.filter(item => item !== level.value) })} />{level.label}</label>)}</div></Field><Field label="Hariç tutulacak kelimeler"><TagInput items={draft.keywords_exclude} onChange={keywords_exclude => update({ keywords_exclude })} placeholder="Kelime ekle" /></Field></section>
      <section className="content-panel form-section"><SectionTitle title="Nerede?" /><Field label="Konumlar"><TagInput items={draft.locations} onChange={locations => update({ locations })} placeholder="Konum ekle" /></Field><label className="toggle-row"><span><strong>Sadece uzaktan</strong><small>Yalnızca remote ilanları göster.</small></span><input type="checkbox" checked={draft.remote_only} onChange={event => update({ remote_only: event.target.checked })} /><span className="switch" /></label></section>
      <section className="content-panel form-section"><SectionTitle title="Eşleşme ve paket" /><Field label={`Minimum uyum puanı: ${draft.min_score}`} hint="Bu puanın üzerindeki ilanlar için paket otomatik hazırlanabilir."><input type="range" min="0" max="100" step="5" value={draft.min_score} onChange={event => update({ min_score: Number(event.target.value) })} /></Field><label className="toggle-row"><span><strong>Paketleri otomatik hazırla</strong><small>Uygun ilanlarda CV ve ön yazı üret.</small></span><input type="checkbox" checked={draft.auto_package} onChange={event => update({ auto_package: event.target.checked })} /><span className="switch" /></label><Field label="CV dili"><select aria-label="CV dili" value={draft.cv_language} onChange={event => update({ cv_language: event.target.value as SearchSettings['cv_language'] })}><option value="auto">İlan diline göre</option><option value="tr">Türkçe</option><option value="en">İngilizce</option></select></Field></section>
      <section className="content-panel form-section"><SectionTitle title="İlan kaynakları" /><p className="section-help">Takip edilecek siteleri ve şirketleri seç.</p>{sourceToggles.map(source => <label className="toggle-row source-toggle" key={source.key}><span><strong>{source.label}</strong></span><input type="checkbox" checked={draft.sources[source.key]} onChange={event => update({ sources: { ...draft.sources, [source.key]: event.target.checked } })} /><span className="switch" /></label>)}<div className="source-company-grid"><Field label="Greenhouse şirketleri" hint="Örnek: job-boards.greenhouse.io/anthropic → anthropic"><TagInput items={draft.sources.greenhouse} onChange={greenhouse => update({ sources: { ...draft.sources, greenhouse } })} placeholder="Şirket adı ekle" /></Field><Field label="Lever şirketleri" hint="Örnek: jobs.lever.co/palantir → palantir"><TagInput items={draft.sources.lever} onChange={lever => update({ sources: { ...draft.sources, lever } })} placeholder="Şirket adı ekle" /></Field><Field label="Ashby şirketleri" hint="Örnek: jobs.ashbyhq.com/ramp → ramp"><TagInput items={draft.sources.ashby} onChange={ashby => update({ sources: { ...draft.sources, ashby } })} placeholder="Şirket adı ekle" /></Field></div><label className="toggle-row"><span><strong>E-posta alarmları</strong><small>LinkedIn, Kariyer.net, Indeed alarm e-postalarını okur. E-posta bilgileri bilgisayardaki .env dosyasında ayarlanır.</small></span><input type="checkbox" checked={draft.sources.email_alerts} onChange={event => update({ sources: { ...draft.sources, email_alerts: event.target.checked } })} /><span className="switch" /></label></section>
      <section className="content-panel form-section"><SectionTitle title="Zamanlama" /><div className="schedule-row"><div className="schedule-icon"><Clock3 size={20} /></div><div><strong>Günlük tarama saati</strong><p>Yeni fırsatlar her gün bu saatte aranır.</p></div><input type="time" aria-label="Günlük tarama saati" value={scheduleTime} onInput={event => setScheduleTime(event.currentTarget.value)} onChange={event => setScheduleTime(event.target.value)} /></div></section>
      {save.error && <p role="alert" className="error-message">{save.error.message}</p>}<div className="form-bottom"><span><SlidersHorizontal size={16} /> {dirty ? 'Kaydedilmemiş değişiklikler var' : 'Tercihlerin güncel'}</span><button className="button primary" disabled={!dirty || save.isPending} onClick={() => save.mutate(draft)}><Check size={17} /> Kaydet</button></div>{auth.tokenRequired && <button className="text-button" disabled={auth.loggingOut} onClick={auth.logout}>{auth.loggingOut ? 'Çıkış yapılıyor…' : 'Bu cihazdan çıkış yap'}</button>}
    </div></div><div className="settings-footnote"><Radar size={17} /> Ayarları kaydettikten sonra yeni ilan aramak için “Şimdi tara”yı kullanabilirsin.</div>
  </>
}
